### ISSUE TITLE
Is your predict function an implementation of your BHITK method ? 

### ISSUE THREAD

**Issue by fmagera** [Paulkie99/KeypointAnnotator#1]
Hi @Paulkie99, 

I was wondering if you released the implementation of your paper ? I would like to test it on the sn-gamestate dataset. 
By any chance, is it already included in this repo in your predict functionality to ease the annotation process ? 
 
Cheers, 
Floriane

**Comment by Paulkie99** [comment]
Hi @fmagera! Thank you for your interest. Regretfully, I have not received permission from my sponsors to release the complete paper implementation. I will ask them again, but I doubt that they will approve.

The predict functionality in this repo only uses the A_t matrix as defined in the paper (which is determined with open-source libraries), without the keypoint and homography KFs.
